FROM php:8.1-cli-alpine
# posible could install cache directory here
RUN  --mount=type=bind,from=mlocati/php-extension-installer:1.5,source=/usr/bin/install-php-extensions,target=/usr/local/bin/install-php-extensions \
      install-php-extensions zip xdebug-stable
RUN addgroup -S app && adduser -S app -G app
RUN mkdir -p /app && chown -R app /app && mkdir -p /tmp && chown -R app /tmp
USER app
WORKDIR /app